/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#0A0A0A',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c0c7d4',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#8b919d',
        'outline-variant': '#414752',
        'surface-tint': '#a2c9ff',
        primary: '#a2c9ff',
        'on-primary': '#00315c',
        'primary-container': '#58a6ff',
        'on-primary-container': '#003a6b',
        'inverse-primary': '#0060aa',
        secondary: '#74dd7e',
        'on-secondary': '#003910',
        'secondary-container': '#007f2d',
        'on-secondary-container': '#c4ffc2',
        tertiary: '#ffb77c',
        'on-tertiary': '#4d2700',
        'tertiary-container': '#e48f43',
        'on-tertiary-container': '#5a2e00',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#d3e4ff',
        'primary-fixed-dim': '#a2c9ff',
        'on-primary-fixed': '#001c38',
        'on-primary-fixed-variant': '#004882',
        'secondary-fixed': '#90fa97',
        'secondary-fixed-dim': '#74dd7e',
        'on-secondary-fixed': '#002106',
        'on-secondary-fixed-variant': '#00531b',
        'tertiary-fixed': '#ffdcc2',
        'tertiary-fixed-dim': '#ffb77c',
        'on-tertiary-fixed': '#2e1500',
        'on-tertiary-fixed-variant': '#6d3900',
        'window-red': '#FF5F56',
        'window-yellow': '#FFBD2E',
        'window-green': '#27C93F',
        'editor-bg': '#161B22',
        'editor-border': '#30363D',
        'editor-header': '#0D1117',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['Space Grotesk', 'monospace'],
        display: ['Space Grotesk', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        h1: ['4.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['2.25rem', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.7', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.6', fontWeight: '400' }],
        'code-md': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['0.75rem', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      animation: {
        blink: 'blink 1s step-end infinite',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
      },
    },
  },
  plugins: [],
}
